
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.lumyk.swiftbindings.ProjectsTypes$UserListener ///

public protocol ProjectsTypes_UserListener: JavaProtocol {

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getAvatarUrl()

    func getAvatarUrl() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getBio()

    func getBio() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getEmail()

    func getEmail() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getId()

    func getId() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLocation()

    func getLocation() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLogin()

    func getLogin() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getName()

    func getName() -> String!

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getUrl()

    func getUrl() -> String!

}


open class ProjectsTypes_UserListenerForward: JNIObjectForward, ProjectsTypes_UserListener {

    private static var ProjectsTypes_UserListenerJNIClass: jclass?

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getAvatarUrl()

    private static var getAvatarUrl_MethodID_9: jmethodID?

    open func getAvatarUrl() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getAvatarUrl", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getAvatarUrl_MethodID_9, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getBio()

    private static var getBio_MethodID_10: jmethodID?

    open func getBio() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getBio", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getBio_MethodID_10, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getEmail()

    private static var getEmail_MethodID_11: jmethodID?

    open func getEmail() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getEmail", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getEmail_MethodID_11, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getId()

    private static var getId_MethodID_12: jmethodID?

    open func getId() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getId", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getId_MethodID_12, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLocation()

    private static var getLocation_MethodID_13: jmethodID?

    open func getLocation() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getLocation", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getLocation_MethodID_13, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLogin()

    private static var getLogin_MethodID_14: jmethodID?

    open func getLogin() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getLogin", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getLogin_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getName()

    private static var getName_MethodID_15: jmethodID?

    open func getName() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getName", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getName_MethodID_15, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getUrl()

    private static var getUrl_MethodID_16: jmethodID?

    open func getUrl() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getUrl", methodSig: "()Ljava/lang/String;", methodCache: &ProjectsTypes_UserListenerForward.getUrl_MethodID_16, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


}

private typealias ProjectsTypes_UserListener_getAvatarUrl_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getAvatarUrl_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getAvatarUrl( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getBio_1_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getBio_1( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getBio( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getEmail_2_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getEmail_2( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getEmail( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getId_3_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getId_3( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getId( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getLocation_4_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getLocation_4( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getLocation( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getLogin_5_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getLogin_5( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getLogin( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getName_6_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getName_6( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getName( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

private typealias ProjectsTypes_UserListener_getUrl_7_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> jobject?

private func ProjectsTypes_UserListener_getUrl_7( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> jobject? {
    let __return = ProjectsTypes_UserListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).getUrl( )
    var __locals = [jobject]()
    return JNI.check( JNIType.toJava( value: __return, locals: &__locals ).l, &__locals, removeLast: true )
}

fileprivate class ProjectsTypes_UserListenerLocal_: JNILocalProxy<ProjectsTypes_UserListener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let ProjectsTypes_UserListener_getAvatarUrl_0_thunk: ProjectsTypes_UserListener_getAvatarUrl_0_type = ProjectsTypes_UserListener_getAvatarUrl_0
        natives.append( JNINativeMethod( name: strdup("__getAvatarUrl"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getAvatarUrl_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getBio_1_thunk: ProjectsTypes_UserListener_getBio_1_type = ProjectsTypes_UserListener_getBio_1
        natives.append( JNINativeMethod( name: strdup("__getBio"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getBio_1_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getEmail_2_thunk: ProjectsTypes_UserListener_getEmail_2_type = ProjectsTypes_UserListener_getEmail_2
        natives.append( JNINativeMethod( name: strdup("__getEmail"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getEmail_2_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getId_3_thunk: ProjectsTypes_UserListener_getId_3_type = ProjectsTypes_UserListener_getId_3
        natives.append( JNINativeMethod( name: strdup("__getId"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getId_3_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getLocation_4_thunk: ProjectsTypes_UserListener_getLocation_4_type = ProjectsTypes_UserListener_getLocation_4
        natives.append( JNINativeMethod( name: strdup("__getLocation"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getLocation_4_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getLogin_5_thunk: ProjectsTypes_UserListener_getLogin_5_type = ProjectsTypes_UserListener_getLogin_5
        natives.append( JNINativeMethod( name: strdup("__getLogin"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getLogin_5_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getName_6_thunk: ProjectsTypes_UserListener_getName_6_type = ProjectsTypes_UserListener_getName_6
        natives.append( JNINativeMethod( name: strdup("__getName"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getName_6_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let ProjectsTypes_UserListener_getUrl_7_thunk: ProjectsTypes_UserListener_getUrl_7_type = ProjectsTypes_UserListener_getUrl_7
        natives.append( JNINativeMethod( name: strdup("__getUrl"), signature: strdup("(J)Ljava/lang/String;"), fnPtr: unsafeBitCast( ProjectsTypes_UserListener_getUrl_7_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        withUnsafePointer(to: &natives[0]) {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_lumyk/ProjectsTypes_UserListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension ProjectsTypes_UserListener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return ProjectsTypes_UserListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class ProjectsTypes_UserListenerBase: ProjectsTypes_UserListener {

    public init() {}

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getAvatarUrl()

    open func getAvatarUrl() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getBio()

    open func getBio() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getEmail()

    open func getEmail() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getId()

    open func getId() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLocation()

    open func getLocation() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLogin()

    open func getLogin() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getName()

    open func getName() -> String! /**/ {
        return nil
    }


    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getUrl()

    open func getUrl() -> String! /**/ {
        return nil
    }


}
