
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.lumyk.swiftbindings.ProjectsBinding ///

public protocol ProjectsBinding: JavaProtocol {

}


open class ProjectsBindingForward: JNIObjectForward, ProjectsBinding {

    private static var ProjectsBindingJNIClass: jclass?

}

