
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.lumyk.swiftbindings.ProjectsTypes ///

public protocol ProjectsTypes: JavaProtocol {

}


open class ProjectsTypesForward: JNIObjectForward, ProjectsTypes {

    private static var ProjectsTypesJNIClass: jclass?

}

