
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.lumyk.swiftbindings.ProjectsBinding$Listener ///

package org.swiftjava.com_lumyk;

@SuppressWarnings("JniMissingFunction")
public class ProjectsBinding_ListenerProxy implements com.lumyk.swiftbindings.ProjectsBinding.Listener {

    // address of proxy object
    long __swiftObject;

    ProjectsBinding_ListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsBinding$Listener.getOauthURL()

    public native java.lang.String __getOauthURL( long __swiftObject );

    public java.lang.String getOauthURL() {
        return __getOauthURL( __swiftObject  );
    }

    /// public abstract void com.lumyk.swiftbindings.ProjectsBinding$Listener.getUser()

    public native void __getUser( long __swiftObject );

    public void getUser() {
        __getUser( __swiftObject  );
    }

    /// public abstract void com.lumyk.swiftbindings.ProjectsBinding$Listener.handleAccessTokenURL(java.lang.String)

    public native void __handleAccessTokenURL( long __swiftObject, java.lang.String url );

    public void handleAccessTokenURL( java.lang.String url ) {
        __handleAccessTokenURL( __swiftObject, url );
    }

    /// public abstract void com.lumyk.swiftbindings.ProjectsBinding$Listener.setCacheDir(java.lang.String)

    public native void __setCacheDir( long __swiftObject, java.lang.String cacheDir );

    public void setCacheDir( java.lang.String cacheDir ) {
        __setCacheDir( __swiftObject, cacheDir );
    }

    /// public abstract void com.lumyk.swiftbindings.ProjectsBinding$Listener.setupAccessToken(java.lang.String)

    public native void __setupAccessToken( long __swiftObject, java.lang.String accessToken );

    public void setupAccessToken( java.lang.String accessToken ) {
        __setupAccessToken( __swiftObject, accessToken );
    }

    /// public abstract void com.lumyk.swiftbindings.ProjectsBinding$Listener.validateAccessToken(java.lang.String)

    public native void __validateAccessToken( long __swiftObject, java.lang.String accessToken );

    public void validateAccessToken( java.lang.String accessToken ) {
        __validateAccessToken( __swiftObject, accessToken );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
