
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.lumyk.swiftbindings.ProjectsTypes$UserListener ///

package org.swiftjava.com_lumyk;

@SuppressWarnings("JniMissingFunction")
public class ProjectsTypes_UserListenerProxy implements com.lumyk.swiftbindings.ProjectsTypes.UserListener {

    // address of proxy object
    long __swiftObject;

    ProjectsTypes_UserListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getAvatarUrl()

    public native java.lang.String __getAvatarUrl( long __swiftObject );

    public java.lang.String getAvatarUrl() {
        return __getAvatarUrl( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getBio()

    public native java.lang.String __getBio( long __swiftObject );

    public java.lang.String getBio() {
        return __getBio( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getEmail()

    public native java.lang.String __getEmail( long __swiftObject );

    public java.lang.String getEmail() {
        return __getEmail( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getId()

    public native java.lang.String __getId( long __swiftObject );

    public java.lang.String getId() {
        return __getId( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLocation()

    public native java.lang.String __getLocation( long __swiftObject );

    public java.lang.String getLocation() {
        return __getLocation( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getLogin()

    public native java.lang.String __getLogin( long __swiftObject );

    public java.lang.String getLogin() {
        return __getLogin( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getName()

    public native java.lang.String __getName( long __swiftObject );

    public java.lang.String getName() {
        return __getName( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$UserListener.getUrl()

    public native java.lang.String __getUrl( long __swiftObject );

    public java.lang.String getUrl() {
        return __getUrl( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
