
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.lumyk.swiftbindings.ProjectsTypes$TextListener ///

package org.swiftjava.com_lumyk;

@SuppressWarnings("JniMissingFunction")
public class ProjectsTypes_TextListenerProxy implements com.lumyk.swiftbindings.ProjectsTypes.TextListener {

    // address of proxy object
    long __swiftObject;

    ProjectsTypes_TextListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$TextListener.getText2()

    public native java.lang.String __getText2( long __swiftObject );

    public java.lang.String getText2() {
        return __getText2( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$TextListener.getText3()

    public native java.lang.String __getText3( long __swiftObject );

    public java.lang.String getText3() {
        return __getText3( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$TextListener.getText4()

    public native java.lang.String __getText4( long __swiftObject );

    public java.lang.String getText4() {
        return __getText4( __swiftObject  );
    }

    /// public abstract java.lang.String com.lumyk.swiftbindings.ProjectsTypes$TextListener.getText5()

    public native java.lang.String __getText5( long __swiftObject );

    public java.lang.String getText5() {
        return __getText5( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
